import type { Metadata } from "next";
import { Inter, Source_Serif_4 } from "next/font/google";
import "./globals.css";

const sansSerif = Inter({
	variable: "--font-sans-serif",
	subsets: ["latin"],
});

const robotoSerif = Source_Serif_4({
	variable: "--font-serif",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${sansSerif.variable} ${robotoSerif.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
