import type { Metadata } from "next";
import { Inter, Source_Serif_4 } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import ThemeToggle from "@/components/theme-toggle";

const sansSerif = Inter({
	variable: "--font-sans-serif",
	subsets: ["latin"],
});

const robotoSerif = Source_Serif_4({
	variable: "--font-serif",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${sansSerif.variable} ${robotoSerif.variable} antialiased`}
			>
				<ThemeProvider attribute="data-theme">
					<header className="flex justify-end px-6 py-4">
						<ThemeToggle className="" />
					</header>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
